// backend/constants/errorCodes.js

const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_INVALID: 'SESSION_INVALID',

  USER_PREFERENCES_NOT_FOUND: 'USER_PREFERENCES_NOT_FOUND',
  USER_PREFERENCES_INVALID: 'USER_PREFERENCES_INVALID',

  HELP_FAQ_NOT_FOUND: 'HELP_FAQ_NOT_FOUND',
  HELP_TICKET_NOT_FOUND: 'HELP_TICKET_NOT_FOUND',
  HELP_INVALID_PAYLOAD: 'HELP_INVALID_PAYLOAD',

  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

module.exports = ERROR_CODES;